# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-25 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book.Author'),
        ),
    ]
